// <auto-generated />
using System;
using FitpalAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitpalAPI.Data.Migrations
{
    [DbContext(typeof(FitpalContext))]
    [Migration("20190514210949_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitpalAPI.Models.Ciudad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("FitpalAPI.Models.TipoEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TipoEntrenamientos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfa9c715-79c4-48dd-91fb-59c3d65e746d"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 610, DateTimeKind.Local).AddTicks(5135),
                            Nombre = "Acroyoga"
                        },
                        new
                        {
                            Id = new Guid("1fce60ac-801c-4c63-ad6f-1ad5bb1bc4a1"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(3562),
                            Nombre = "Aeroyoga"
                        },
                        new
                        {
                            Id = new Guid("c394e6fc-3c60-4bc2-9cfe-e63d2068fdda"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(3730),
                            Nombre = "Artes Marciales"
                        },
                        new
                        {
                            Id = new Guid("300fc523-5b27-4cb7-a48f-9b69f0eab5f7"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(3756),
                            Nombre = "Baile/Danza"
                        },
                        new
                        {
                            Id = new Guid("ddca972d-6c9f-4e68-af06-1bcceb886a8a"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(3778),
                            Nombre = "Barre"
                        },
                        new
                        {
                            Id = new Guid("1fc660c4-8101-4976-ba67-49651a93e6f7"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(3911),
                            Nombre = "Bienestar"
                        },
                        new
                        {
                            Id = new Guid("d12ebc3f-dff2-4c3a-8506-9bc3d8b8739a"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(3934),
                            Nombre = "Boxeo"
                        },
                        new
                        {
                            Id = new Guid("bca308b9-3325-4643-8fc8-0bfc382e94a4"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(3972),
                            Nombre = "Complementa tu entrenamiento!"
                        },
                        new
                        {
                            Id = new Guid("b7c717b2-d9ee-4755-926b-e379899ba36e"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(3995),
                            Nombre = "Crossfit"
                        },
                        new
                        {
                            Id = new Guid("1e3ea8ab-8e16-43a2-9d00-bf82fb6ea410"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4021),
                            Nombre = "Crosstraining"
                        },
                        new
                        {
                            Id = new Guid("f6a3298a-b5f8-4299-893d-5c3f47e23158"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4043),
                            Nombre = "Deportes"
                        },
                        new
                        {
                            Id = new Guid("ee128988-182c-4e11-8b62-d97fcd1f30e9"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4066),
                            Nombre = "EMS"
                        },
                        new
                        {
                            Id = new Guid("3b626613-40e8-4aae-b7e3-602043847def"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4087),
                            Nombre = "Entrenamiento personalizado"
                        },
                        new
                        {
                            Id = new Guid("1e1d5687-6cb6-46e3-a3d2-f57ad2f089d5"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4110),
                            Nombre = "Esferokinosis®"
                        },
                        new
                        {
                            Id = new Guid("51d589d5-e439-46da-81d8-afec27b117e5"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4131),
                            Nombre = "Funcional"
                        },
                        new
                        {
                            Id = new Guid("954e918a-40e1-4423-8d33-11417d5ea209"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4157),
                            Nombre = "Gimnasia Rítmica Expresiva"
                        },
                        new
                        {
                            Id = new Guid("b88b481b-3be9-44e9-8bc5-99f25374f333"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4180),
                            Nombre = "Golfito"
                        },
                        new
                        {
                            Id = new Guid("7bc4de6e-11c6-452a-a663-308d4ce24cf8"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4204),
                            Nombre = "Gym time"
                        },
                        new
                        {
                            Id = new Guid("06096371-66ef-4e33-93f4-0db7fa942c26"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4225),
                            Nombre = "HIIT"
                        },
                        new
                        {
                            Id = new Guid("d2845a3d-1a0a-4366-a837-e8f3a32445b6"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4246),
                            Nombre = "Indoor Cycling"
                        },
                        new
                        {
                            Id = new Guid("1002f2ee-d8f6-45c2-bdef-e2afd5229001"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4269),
                            Nombre = "Jiu Jitsu Brasilero"
                        },
                        new
                        {
                            Id = new Guid("bbd40883-8bf3-4dd6-a5f8-5c881bdddfbd"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4291),
                            Nombre = "Karate"
                        },
                        new
                        {
                            Id = new Guid("7fa30c8c-f558-4f7b-a2e1-9d1b345aa557"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4312),
                            Nombre = "Kids"
                        },
                        new
                        {
                            Id = new Guid("2870eebc-697b-4e0a-8c92-15817f5ae49f"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4338),
                            Nombre = "Levantamiento de pesas"
                        },
                        new
                        {
                            Id = new Guid("4bf8a457-0efe-47ac-b932-2165712c9253"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4363),
                            Nombre = "Lucha Olímpica"
                        },
                        new
                        {
                            Id = new Guid("c6139892-7ebf-498f-a900-df0296be0359"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4384),
                            Nombre = "Muay Thai - Kick Boxing"
                        },
                        new
                        {
                            Id = new Guid("8b8edc14-fe3c-45c5-9556-5bf66aadabdc"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4406),
                            Nombre = "Natación"
                        },
                        new
                        {
                            Id = new Guid("af87fceb-9eaf-47f9-aa7c-4ab6381d93fe"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4427),
                            Nombre = "Pilates"
                        },
                        new
                        {
                            Id = new Guid("ec0e08fc-c0df-449d-89b2-d6944c65d059"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4449),
                            Nombre = "Power plate"
                        },
                        new
                        {
                            Id = new Guid("8c28b79c-0e03-4029-9759-8d99a176be05"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4470),
                            Nombre = "Sauna/Turco"
                        },
                        new
                        {
                            Id = new Guid("0a48cf19-7a3a-4a70-8dfa-8cfa84652a80"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4491),
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = new Guid("02512d2c-b241-459b-842e-eb15ad1faaac"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4517),
                            Nombre = "Tenis"
                        },
                        new
                        {
                            Id = new Guid("370a8aee-b8ab-4051-8a01-e736602bbad4"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4541),
                            Nombre = "Valoración Física"
                        },
                        new
                        {
                            Id = new Guid("5bd46f30-43dd-4530-a669-d4e5a0632f4f"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4564),
                            Nombre = "Weight Lifting"
                        },
                        new
                        {
                            Id = new Guid("682965b5-6014-4da5-82c7-9a340a63972d"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4659),
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = new Guid("64672e68-22dd-43c8-8d68-a5cc3d938f29"),
                            FechaCreacion = new DateTime(2019, 5, 14, 16, 9, 48, 613, DateTimeKind.Local).AddTicks(4681),
                            Nombre = "Yoga pilates"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
